# Generated by Django 6.0.3 on 2026-06-23 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0006_school_school_email_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], max_length=10)),
                ('recipient_type', models.CharField(choices=[('all_students', 'All Students'), ('all_staff', 'All Staff'), ('specific_students', 'Specific Students'), ('specific_staff', 'Specific Staff'), ('class', 'Whole Class'), ('guardians_of', 'Guardians of Students')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Filter criteria or extra data')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('guardian', 'Guardian'), ('user', 'User')], max_length=10)),
                ('recipient_id', models.UUIDField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_contact', models.CharField(blank=True, help_text='Email or phone used', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.notification')),
            ],
            options={
                'ordering': ['recipient_name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=200)),
                ('body', models.TextField(help_text='Message body. Use {{variable_name}} for placeholders.')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default='email', max_length=10)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names used in the template')),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communications.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('twilio', 'Twilio'), ('africas_talking', "Africa's Talking")], max_length=30)),
                ('config', models.JSONField(default=dict, help_text='Provider credentials and settings')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_providers', to='schools.school')),
            ],
            options={
                'ordering': ['channel', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
