# Generated by Django 6.0.3 on 2026-06-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprovider',
            name='provider_type',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('mnotify', 'mNotify'), ('arkesel', 'Arkesel')], max_length=30),
        ),
    ]
