# Generated by Django 6.0.3 on 2026-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_notificationprovider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprovider',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], max_length=10),
        ),
    ]
