# Generated by Django 6.0.3 on 2026-06-19 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('schools', '0006_school_school_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='schools.school'),
        ),
    ]
