# Generated by Django 6.0.3 on 2026-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
