# Generated by Django 6.0.3 on 2026-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_options_staffprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='notes',
        ),
    ]
