# Generated by Django 6.0.3 on 2026-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('finance_manager', 'Finance Manager'), ('superadmin', 'Super Admin')], default='teacher', max_length=20),
        ),
    ]
