# Generated by Django 6.0.3 on 2026-04-17 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='name of assessment type', max_length=100)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(help_text='School for this assessment type', on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_school_assessment_name')],
            },
        ),
    ]
