# Generated by Django 6.0.3 on 2026-04-17 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subjectteacher'),
        ('exams', '0001_initial'),
        ('schools', '0002_school_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g Primary Division report scheme', max_length=100)),
                ('sba_scaling', models.DecimalField(decimal_places=2, default=50, help_text='Weight for SBA (e.g 40 for 40%)', max_digits=5)),
                ('exam_scaling', models.DecimalField(decimal_places=2, default=50, help_text='Weight for Main exam (e.g 60 for 60%)', max_digits=5)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('main_exam', models.ForeignKey(help_text='the assessment that serve as the main exam', on_delete=django.db.models.deletion.PROTECT, related_name='exam_report_schemes', to='exams.assessmenttype')),
                ('sba_components', models.ManyToManyField(help_text='the assessments that contribute to the SBA components', related_name='sba_report_schemes', to='exams.assessmenttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'term', 'name'), name='unique_scheme_name_per_term')],
            },
        ),
    ]
