# Generated by Django 6.0.3 on 2026-04-20 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subjectteacher'),
        ('exams', '0002_reportscheme'),
        ('schools', '0002_school_onboarding_completed'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teacher_remarks', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.assessmenttype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_marks', to='staff.staffprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'ordering': ['student', 'assessment', 'term', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('student', 'assessment', 'term', 'subject', 'student_class'), name='unique_student_assessment_score')],
            },
        ),
    ]
