# Generated by Django 6.0.3 on 2026-04-20 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subjectteacher'),
        ('exams', '0003_studentmark'),
        ('schools', '0002_school_onboarding_completed'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportscheme',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes that this report scheme applies to.', related_name='report_schemes', to='academics.class'),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_attendance', models.PositiveSmallIntegerField(default=0, help_text='Number of days attended')),
                ('total_school_days', models.PositiveSmallIntegerField(default=0, help_text='Total number of school days in the term')),
                ('teacher_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PUBLISHED', 'Published'), ('PENDING_REMARKS', 'Pending Remarks')], default='DRAFT', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('report_scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.reportscheme')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reports', to='staff.staffprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'ordering': ['student', 'term', 'academic_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentReportSubjectScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sba_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('student_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='exams.studentreport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
            ],
            options={
                'ordering': ['student_report', 'subject'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentreport',
            constraint=models.UniqueConstraint(fields=('student', 'term', 'student_class'), name='unique_student_report_per_term_year'),
        ),
        migrations.AddConstraint(
            model_name='studentreportsubjectscore',
            constraint=models.UniqueConstraint(fields=('student_report', 'subject'), name='unique_subject_score_per_report'),
        ),
    ]
