# Generated by Django 6.0.3 on 2026-04-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_reportscheme_assigned_classes_studentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreportsubjectscore',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
