# Generated by Django 6.0.3 on 2026-04-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentreportsubjectscore_rank'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreportsubjectscore',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_subject_scores', to='students.student'),
        ),
    ]
