# Generated by Django 6.0.3 on 2026-06-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_studentreportsubjectscore_student'),
        ('schools', '0006_school_school_email_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportscheme',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='assessmenttype',
            name='unique_school_assessment_name',
        ),
        migrations.RemoveConstraint(
            model_name='reportscheme',
            name='unique_scheme_name_per_term',
        ),
        migrations.AlterUniqueTogether(
            name='assessmenttype',
            unique_together={('school', 'name')},
        ),
        migrations.RemoveField(
            model_name='reportscheme',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='reportscheme',
            name='assigned_classes',
        ),
        migrations.RemoveField(
            model_name='reportscheme',
            name='term',
        ),
    ]
