# Generated by Django 6.0.3 on 2026-06-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_studentreportsubjectscore_grade'),
        ('schools', '0006_school_school_email_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportscheme',
            options={},
        ),
        migrations.AddField(
            model_name='studentreport',
            name='overall_position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='reportscheme',
            constraint=models.UniqueConstraint(fields=('name', 'school'), name='unique_reportscheme_per_school'),
        ),
    ]
