# Generated by Django 6.0.3 on 2026-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_reportscheme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='headteacher_remarks',
            field=models.TextField(blank=True),
        ),
    ]
