# Generated by Django 6.0.3 on 2026-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_studentreport_headteacher_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
