# Generated by Django 6.0.3 on 2026-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_studentreport_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='headteacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
