# Generated by Django 6.0.3 on 2026-03-27 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('lite', 'Lite'), ('advantage', 'Advantage'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('price_per_term', models.DecimalField(decimal_places=2, default=0, help_text='Price in GHS per academic term', max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time setup fee in GHS', max_digits=10)),
                ('min_students', models.PositiveIntegerField(default=0, help_text='Minimum student count for this plan')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum student count. null = unlimited', null=True)),
                ('has_student_records', models.BooleanField(default=True)),
                ('has_class_subject_setup', models.BooleanField(default=True)),
                ('has_score_entry', models.BooleanField(default=True)),
                ('has_report_cards', models.BooleanField(default=True)),
                ('has_basic_broadsheet', models.BooleanField(default=True)),
                ('has_fee_billing', models.BooleanField(default=True)),
                ('has_payment_tracking', models.BooleanField(default=True)),
                ('has_debtors_list', models.BooleanField(default=True)),
                ('has_sms_alerts', models.BooleanField(default=True)),
                ('has_admin_teacher_portal', models.BooleanField(default=True)),
                ('has_advanced_finance', models.BooleanField(default=False)),
                ('has_income_expense_tracking', models.BooleanField(default=False)),
                ('has_full_broadsheet', models.BooleanField(default=False)),
                ('has_term_comparison', models.BooleanField(default=False)),
                ('has_audit_logs', models.BooleanField(default=False)),
                ('has_announcements', models.BooleanField(default=False)),
                ('has_extended_sms', models.BooleanField(default=False)),
                ('has_student_portal', models.BooleanField(default=False)),
                ('has_export', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_multi_year_tracking', models.BooleanField(default=False)),
                ('has_department_access_control', models.BooleanField(default=False)),
                ('has_custom_report_cards', models.BooleanField(default=False)),
                ('has_custom_report_formats', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('has_data_migration', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_per_term'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('grace', 'Grace Period'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('grace_end_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Term subscription amount paid in GHS', max_digits=10, null=True)),
                ('setup_fee_paid', models.BooleanField(default=False, help_text='Whether the one-time setup fee has been collected')),
                ('setup_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_provider', models.CharField(blank=True, help_text='e.g. paystack, momo, manual', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schools.school')),
                ('term', models.ForeignKey(blank=True, help_text='The academic term this subscription covers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='academics.term')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
