# Generated by Django 6.0.3 on 2026-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_has_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
