# Generated by Django 6.0.3 on 2026-05-28 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='setup_fee_amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='setup_fee_paid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('grace', 'Grace Period'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
