# Generated by Django 6.0.3 on 2026-04-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
