# Generated by Django 6.0.3 on 2026-05-25 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
