# Generated by Django 6.0.3 on 2026-05-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='is_active',
        ),
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
