# Generated by Django 6.0.3 on 2026-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_remove_school_is_active_school_school_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_email_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
