# Generated by Django 6.0.3 on 2026-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='next_reopening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
