# Generated by Django 6.0.3 on 2026-04-15 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_term_next_reopening_date'),
        ('schools', '0002_school_onboarding_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together={('school', 'klass', 'academic_year', 'teacher')},
        ),
    ]
