# Generated by Django 6.0.3 on 2026-04-16 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classteacher_unique_together'),
        ('schools', '0002_school_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=True)),
                ('max_score', models.PositiveBigIntegerField(default=100, help_text='Maximum possible score for the grade system')),
                ('pass_mark', models.PositiveBigIntegerField(default=50, help_text='Minimum score considered a pass.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(help_text='Grade label e.g A1, B2', max_length=10)),
                ('label', models.CharField(help_text='Descriptive label e.g Excellent, Very good', max_length=50)),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Minimum score for this grade (inclusive)', max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum score for this grade (inclusive)', max_digits=5)),
                ('is_passing', models.BooleanField(default=True, help_text='Whether is grade is considered as a passing grade')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order — lower number appears first.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('grade_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.gradingsystem')),
            ],
            options={
                'ordering': ['grade_system', 'position', '-min_score'],
                'unique_together': {('grade_system', 'grade')},
            },
        ),
    ]
