# Generated by Django 6.0.3 on 2026-04-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_gradingsystem_gradescale'),
        ('schools', '0002_school_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='remark',
            field=models.CharField(blank=True, help_text="Optional remark e.g 'Distinction', 'Credit', 'Fail'", max_length=100),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='grade_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.gradingsystem'),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_systems', to='schools.school'),
        ),
    ]
