# Generated by Django 6.0.3 on 2026-04-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_gradescale_remark_alter_gradescale_grade_system_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradescale',
            options={'ordering': ['grading_system', 'position', '-min_score']},
        ),
        migrations.RenameField(
            model_name='gradescale',
            old_name='grade_system',
            new_name='grading_system',
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('grading_system', 'grade')},
        ),
    ]
