# Generated by Django 6.0.3 on 2026-04-17 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_gradescale_options_and_more'),
        ('schools', '0002_school_onboarding_completed'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.academicyear')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='schools.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='staff.staffprofile')),
                ('term', models.ForeignKey(blank=True, help_text='Optional — if not set applies to the entire year.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.term')),
            ],
            options={
                'ordering': ['klass', 'subject'],
                'unique_together': {('school', 'klass', 'subject', 'academic_year', 'term')},
            },
        ),
    ]
