# Generated by Django 6.0.3 on 2026-06-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_timetableslot'),
        ('staff', '0003_remove_staffprofile_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='academics.academicyear'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='staff.staffprofile'),
        ),
    ]
