# Generated by Django 6.0.3 on 2026-06-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_classteacher_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacher',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academics.academicyear'),
        ),
    ]
