# Generated by Django 6.0.3 on 2026-06-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_subjectteacher_academic_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradingsystem',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='gradingsystem',
            name='is_default',
        ),
    ]
