# Generated by Django 6.0.3 on 2026-06-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_gradingsystem_options_remove_gradescale_remark_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('grading_system', 'grade'), ('grading_system', 'position')},
        ),
    ]
